TreeBuilder Symfony 5.x constructor update
alexpozzi/pimcore-ldap-bundle pull request #17
Opened 2021-04-22 08:09 UTC by palazzetti

New constructor at https://github.com/symfony/symfony/blob/8361713367e2735fd9b63cd2b6661411a0339811/src/Symfony/Component/Config/Definition/Builder/TreeBuilder.php#L26

2021-04-22 09:50 UTC, BlackbitNeueMedien commented
Can we find a solution which is also compatible with https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Config/Definition/Builder/TreeBuilder.php?

2021-04-29 11:44 UTC, palazzetti commented
> Can we find a solution which is also compatible with https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Config/Definition/Builder/TreeBuilder.php?

Done

2021-04-29 11:52 UTC, BlackbitNeueMedien requested changes

2021-04-29 11:52 UTC, BlackbitNeueMedien commented on src/DependencyInjection/Configuration.php
> +        if ($kernelVersion > 5) {
> 5 or >= 5?

2021-04-29 11:53 UTC, palazzetti commented on src/DependencyInjection/Configuration.php
> +        if ($kernelVersion > 5) {
You are right, >= 5

2021-04-29 11:56 UTC, merged

2021-04-29 11:57 UTC, BlackbitNeueMedien commented
Thanks a lot! Are you yet using this bundle with Pimcore 10?

2021-04-29 11:59 UTC, palazzetti commented
> Thanks a lot! Are you yet using this bundle with Pimcore 10?

Yes and I have no problems, good project 👍